version: '3.5'

services:
  bot:
    build: .
    image: labbsr0x/big-brother-bot:latest
    environment:
      - ETCD_URLS=http://etcd:2379
      - TELEGRAM_TOKEN=<your telegram token>
      - DEBUG=*
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/test:/app/test
    ports:
      - 3000:3000

  etcd:
    image: quay.io/coreos/etcd:v3.2.25
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  alertmanager:
    image: labbsr0x/big-brother-alertmanager
    ports:
      - 9093:9093
    environment:
      - WEBHOOK_URL=http://bot:3000/alertmanager
    volumes:
      - alertmanager:/alertmanager

  # below is defined the example setup for metric consumption by big brother

  example-service:
    image: abilioesteves/metrics-generator:latest
    depends_on:
      - example-etcd
    ports:
      - 32865:32865
    environment:
      - REGISTRY_SERVICE=example-service
      - REGISTRY_ETCD_BASE=/metrics-generator
      - REGISTRY_ETCD_URL=http://example-etcd:2379
  
  example-etcd:
    image: quay.io/coreos/etcd:v3.2.25
    ports:
      - 2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://example-etcd:2379
  
  example-bb-promster:
    image: labbsr0x/bb-promster:latest
    depends_on:
      - example-etcd
      - example-service
    ports:
      - 9091:9090
    environment:
      - REGISTRY_SERVICE=example-service
      - REGISTRY_ETCD_BASE=/metrics-generator
      - BB_PROMSTER_LEVEL=1
      - ETCD_URLS=http://example-etcd:2379
      - SCRAPE_ETCD_PATH=/metrics-generator/example-service
      - ALERT_MANAGER_URLS=alertmanager:9093

volumes:
  bot:
  alertmanager: